JMW/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("back_end/", admin.site.urls),
    path("", include("home.urls")),
    path("accounts/", include("accounts.urls")),
    path("orders/", include("orders.urls")),
    path("payment/", include("payment.urls")),
    path("nysc/", include("nysc.urls")),
    path("cart/", include("cart.urls")),
    path("accounts/", include("allauth.urls")),
    path("ratings/", include("star_ratings.urls", namespace="ratings")),
]

home/urls.py
from django.urls import path
from .views import (
    Photos,
    DetailPhotoView,
    HomeCreateView,
    ContactDeleteView,
    NzeStan,
    Inspos,
    DetailInspoView,
    AboutUsView,
    ContactUsView,
)

urlpatterns = [
    path("", HomeCreateView.as_view(), name="home"),
    path("photo/", Photos.as_view(), name="photo"),
    path("detail_photo/<uuid:pk>/", DetailPhotoView.as_view(), name="detail_photo"),
    path("inspo/", Inspos.as_view(), name="inspo"),
    path("detail_inspo/<uuid:pk>/", DetailInspoView.as_view(), name="detail_inspo"),
    path("nze_stan/", NzeStan.as_view(), name="nze_stan"),
    path(
        "contact_us_delete/<uuid:pk>",
        ContactDeleteView.as_view(),
        name="contact_us_delete",
    ),
    path("about_us/", AboutUsView.as_view(), name="about_us"),
    path("contact_us/", ContactUsView.as_view(), name="contact_us"),
]

home/models.py
from django.db import models
from django.urls import reverse
import uuid


# Create your models here.
class Photo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    image = models.ImageField(upload_to="jume_images/", blank=True)

    def get_absolute_url(self):
        return reverse("detail_photo", args=[str(self.id)])


class Inspo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    inspo = models.ImageField(upload_to="jume_inspos/", blank=True)

    def get_absolute_url(self):
        return reverse("detail_inspo", args=[str(self.id)])


class Contact(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=150)
    email = models.EmailField()
    message = models.TextField()

nysc/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


# Create your models here.
class Product(models.Model):
    TYPE_CHOICES = [
        ("kakhi", "kakhi"),
        ("vest", "vest"),
        ("cap", "cap"),
        # Add more choices as needed
    ]
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to="jume_nysc_products", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    size = models.CharField(max_length=10, default="M", blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("nysc_detail", args=[str(self.id)])

    class Meta:
        ordering = ["id"]


class Measurement(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)
    chest = models.IntegerField(null=True)
    shoulder = models.IntegerField(null=True)
    neck = models.IntegerField(null=True)
    sleeve_length = models.IntegerField(null=True)
    sleeve_round = models.IntegerField(null=True)
    top_length = models.IntegerField(null=True)
    waist = models.IntegerField(null=True)
    thigh = models.IntegerField(null=True)
    ankle = models.IntegerField(null=True)
    laps = models.IntegerField(null=True)
    knee = models.IntegerField(null=True)
    trouser_length = models.IntegerField(null=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("update_measurement", args=[str(self.id)])

home/views.py
from django.views.generic import ListView, DetailView, DeleteView, TemplateView
from django.views.generic.edit import CreateView
from .models import Photo, Contact, Inspo
from django.urls import reverse_lazy


class HomeCreateView(TemplateView):
    template_name = "home.html"


class Photos(ListView):
    model = Photo
    template_name = "photo.html"
    paginate_by = 10
    ordering = ["pk"]


class DetailPhotoView(DetailView):
    model = Photo
    template_name = "detail_photo.html"


class Inspos(ListView):
    model = Inspo
    template_name = "inspo.html"
    paginate_by = 10
    ordering = ["pk"]


class DetailInspoView(DetailView):
    model = Inspo
    template_name = "detail_inspo.html"


class NzeStan(ListView):
    model = Contact
    template_name = "nze.html"
    context_object_name = "contacts"


class ContactDeleteView(DeleteView):
    model = Contact
    template_name = "contact_delete_view.html"
    success_url = reverse_lazy("nze_stan")


class AboutUsView(TemplateView):
    template_name = "about_us.html"


class ContactUsView(CreateView):
    model = Contact
    template_name = "contact_us.html"
    fields = ["name", "email", "message"]
    success_url = reverse_lazy("contact_us")

templates/add_review.html
{% extends "_base.html" %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit Review</button>
</form>


{% endblock content %}

templates/canceled.html
{% extends "_base.html" %}

{% block title %}Payment Unsuccessful{% endblock %}

{% block content %}
<div class="bg-white p-8 rounded-lg shadow-md max-w-md w-full">
    <img src="https://res.cloudinary.com/dhhaiy58r/image/upload/v1707154344/failed_ny3rgb.png" alt="Error Icon"
        class="mx-auto mb-6">

    <h1 class="text-2xl font-semibold text-red-600 mb-4">Payment Unsuccessful</h1>

    <p class="text-gray-600 mb-6">
        Unfortunately, there was an issue with your payment. Please try again.
    </p>

    <a href="{% url 'nysc_landing'%}"
        class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 transition duration-300 block text-center">
        Return to Homepage
    </a>
</div>

<div class="mt-8 text-center">
    <p class="text-gray-700">If the issue persists, contact support for assistance.</p>
</div>
{% endblock content %}
{% block absolute_links %}

{% endblock absolute_links %}

templates/coming_soon.html
{% extends "_base.html" %}

{% block content %}
<div id="about" class="grid grid-cols-1 md:grid-cols-2 gap-3">
    <div class="col-span-1 md:col-span-2">
        <video class="w-full h-full object-cover" autoplay loop muted playsinline>
            <source
                src="https://res.cloudinary.com/dhhaiy58r/video/upload/v1716391092/Black_and_Pink_Modern_Coming_Soon_Instagram_Story_emweby.mp4"
                type="video/mp4">
            Your browser does not support the video tag.
        </video>
    </div>
</div>

{% endblock content %}

{% block absolute_links %}
<!-- Additional links or content can be added here if needed -->
{% endblock absolute_links %}

templates/create_measurement.html
{% extends "_base.html" %}
{% block title %}Create Measurement{% endblock title %}

{% block content %}
<form method="post" class="max-w-sm mx-auto">
    {% csrf_token %}
    <div class="mb-5">
        <label for="id_chest" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Chest
            (inches)</label>
        <input type="number" id="id_chest" name="chest"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_shoulder" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Shoulder
            (inches)</label>
        <input type="number" id="id_shoulder" name="shoulder"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_neck" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Neck (inches)</label>
        <input type="number" id="id_neck" name="neck"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_sleeve_length" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Sleeve
            Length (inches)</label>
        <input type="number" id="id_sleeve_length" name="sleeve_length"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_sleeve_round" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Sleeve
            Round (inches)</label>
        <input type="number" id="id_sleeve_round" name="sleeve_round"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_top_length" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Top
            Length (inches)</label>
        <input type="number" id="id_top_length" name="top_length"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_waist" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Waist
            (inches)</label>
        <input type="number" id="id_waist" name="waist"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_thigh" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Thigh
            (inches)</label>
        <input type="number" id="id_thigh" name="thigh"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_ankle" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Ankle
            (inches)</label>
        <input type="number" id="id_ankle" name="ankle"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_laps" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Laps (inches)</label>
        <input type="number" id="id_laps" name="laps"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_knee" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Knee (inches)</label>
        <input type="number" id="id_knee" name="knee"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_trouser_length" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Trouser
            Length (inches)</label>
        <input type="number" id="id_trouser_length" name="trouser_length"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>

    <br>
    <button type="submit"
        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Create</button>
</form>

{% endblock content %}

{% block absolute_links %}

{% endblock absolute_links %}

templates/detail_inspo.html
{% extends "_base.html" %}

{% block content %}
<a href="{% url 'inspo' %}">
    <button type="button"
        class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Back</button>
</a>

<div class="flex flex-col items-center mt-4">

    {% if inspo.inspo %}
    <img src="{{ inspo.inspo.url }}" class="rounded-[2rem] w-full h-full object-cover" alt="inspo_details">
    {% else %}
    <img src="https://res.cloudinary.com/dhhaiy58r/image/upload/v1716475069/media/jume_images/thumbnail_asocbc.svg"
        class="rounded-[2rem] w-full h-full object-cover" alt="No image available">
    {% endif %}
</div>
<br>
{% if inspo.inspo %}
<a class="grid justify-center whatsapp-icon" href="#"
    onclick="sendWhatsAppMessage('{{ inspo.inspo.url }}'); return false;">
    <img width="100px" height="100px"
        src="https://res.cloudinary.com/dhhaiy58r/image/upload/v1704207702/WhatsApp-Logo.wine_nbsnhs.png"
        alt="whatsapp_LOGO">
</a>
{% endif %}
</div>

{% endblock content %}

{% block absolute_links %}

{% endblock absolute_links %}

templates/state_Abia.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abia</title>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td,
        th {
            border: 1px solid #dddddd;
            text-align: center;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        /* Measurement table styles */
        table.measurement {
            font-family: 'Roboto Condensed', sans-serif;
            font-size: 0.8rem;
            /* Allow table to break across pages */
            prince-table-layout: auto;
        }

        table.measurement th,
        table.measurement td {
            padding: 0.2rem;
        }

        table.measurement tr {
            /* Repeat table header on each new page */
            prince-header-row: repeat(1);
        }

        /* Adjust PDF page size and orientation */
        @page {
            size: A4 landscape;
        }

        /* Make the measurement table responsive */
        @media (max-width: 767px) {
            table.measurement {
                font-size: 0.7rem;
            }

            table.measurement th,
            table.measurement td {
                padding: 0.1rem;
            }
        }
    </style>
</head>

<body>
    <h2>ABIA</h2>

    <table>
        <tr>
            <th>ORDER ID</th>
            <th>NAME</th>
            <th>CALL UP NUMBER</th>
            <th>PHONE NUMBER</th>
            <th>ITEM</th>
            <th>SIZE</th>
            <th>QUANTITY</th>
        </tr>
        {% for order_item in order_items %}

        <tr>
            <td>{{order_item.order.id}}</td>
            <td>{{order_item.user.last_name}} {{order_item.user.first_name}}</td>
            <td>{{order_item.user.nysc_call_up_number}}</td>
            <td>{{order_item.user.phone_number}}</td>
            <td>{{order_item.product.name}}</td>
            <td>{{order_item.product.size}}</td>
            <td>{{order_item.quantity}}</td>
        </tr>

        {% endfor%}
    </table><br>

    <h1>SUMMARY</h1>
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Size</th>
                <th>Total Count</th>
                <th>Total Sum</th>
            </tr>
        </thead>
        <tbody>
            {% for item in summary_query %}
            <tr>
                <td>{{ item.product__name }}</td>
                <td>{{ item.product__size }}</td>
                <td>{{ item.total_count }}</td>
                <td>{{ item.total_sum }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h1>MEASUREMENT</h1>
    <table class="measurement">
        <thead>
            <tr>
                <th>ORDER ID</th>
                <th>CHEST</th>
                <th>SHOULDER</th>
                <th>NECK</th>
                <th>SLEEVE LENGTH</th>
                <th>SLEEVE ROUND</th>
                <th>TOP LENGTH</th>
                <th>WAIST</th>
                <th>THIGH</th>
                <th>ANKLE</th>
                <th>LAPS</th>
                <th>KNEE</th>
                <th>TROUSER LENGTH</th>
            </tr>
        </thead>
        <tbody>
            {% for order_measure in order_items %}
            {% if order_measure.order.paid == True and order_measure.product.type == "kakhi" %}
            <tr>
                <td>{{ order_measure.order.id }}</td>
                <td>{{ order_measure.measurement.chest }}</td>
                <td>{{ order_measure.measurement.shoulder }}</td>
                <td>{{ order_measure.measurement.neck }}</td>
                <td>{{ order_measure.measurement.sleeve_length }}</td>
                <td>{{ order_measure.measurement.sleeve_round }}</td>
                <td>{{ order_measure.measurement.top_length }}</td>
                <td>{{ order_measure.measurement.waist }}</td>
                <td>{{ order_measure.measurement.thigh }}</td>
                <td>{{ order_measure.measurement.ankle }}</td>
                <td>{{ order_measure.measurement.laps }}</td>
                <td>{{ order_measure.measurement.knee }}</td>
                <td>{{ order_measure.measurement.trouser_length }}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</body>

</html>

templates/update_measurement.html
{% extends "_base.html" %}

{% block content %}


<form method="post" class="max-w-sm mx-auto">
    {% csrf_token %}
    <div class="mb-5">
        <label for="id_chest" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Chest
            (inches)</label>
        <input type="number" id="id_chest" name="chest" value="{{measurement.chest}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_shoulder" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Shoulder
            (inches)</label>
        <input type="number" id="id_shoulder" name="shoulder" value="{{measurement.shoulder}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_neck" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Neck (inches)</label>
        <input type="number" id="id_neck" name="neck" value="{{measurement.neck}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_sleeve_length" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Sleeve
            Length (inches)</label>
        <input type="number" id="id_sleeve_length" name="sleeve_length" value="{{measurement.sleeve_length}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_sleeve_round" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Sleeve
            Round (inches)</label>
        <input type="number" id="id_sleeve_round" name="sleeve_round" value="{{measurement.sleeve_round}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_top_length" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Top
            Length (inches)</label>
        <input type="number" id="id_top_length" name="top_length" value="{{measurement.top_length}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_waist" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Waist
            (inches)</label>
        <input type="number" id="id_waist" name="waist" value="{{measurement.waist}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_thigh" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Thigh
            (inches)</label>
        <input type="number" id="id_thigh" name="thigh" value="{{measurement.thigh}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_ankle" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Ankle
            (inches)</label>
        <input type="number" id="id_ankle" name="ankle" value="{{measurement.ankle}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_laps" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Laps (inches)</label>
        <input type="number" id="id_laps" name="laps" value="{{measurement.laps}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_knee" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Knee (inches)</label>
        <input type="number" id="id_knee" name="knee" value="{{measurement.knee}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>
    <div class="mb-5">
        <label for="id_trouser_length" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Trouser
            Length (inches)</label>
        <input type="number" id="id_trouser_length" name="trouser_length" value="{{measurement.trouser_length}}"
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
    </div>

    <br>
    <button type="submit"
        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Update</button>
</form>

{% endblock content %}
{% block absolute_links %}

{% endblock absolute_links %}